# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1758b2f4bb73623722632580b1718539f9b36870cdca80968b2f4a34abdfeb6a0bcd7737a0258363f4f6884f2a8c5eb05c2b64d3a0052cda2fabc0e6490e084b

test:
  secret_key_base: c0b02d42e98ed850f0b30c872c310b83653e4e2c682ed063c4922a2138103b13eccc07668ca6e7aa63f81782867fa092789570e7b0b33d085c99c32bdff79c69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
